# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist


# Site settings
title: "Mushycode"
description: > # this means to ignore newlines until "email:"
   My thoughtsdump and playground

permalink: /:slug:output_ext

email: arunvarghese88@gmail.com
#blog logo
logo: "/assets/images/av.svg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/idea-2924175.png"

name: 'Arun Varghese'
author: 'Arun Varghese'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://mushycode.in" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@mushyinks'

#fill in disqus shortname to use disqus
disqus: mushycode

google_analytics: G-ZFL457VQ7D

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mushyinks
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mushycode
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
